### ISSUE TITLE
[BE] feat: 캠핑장 좋아요 기능 구현 

### ISSUE THREAD

**Issue by cheesecat47** [d106-campu/campu#105]
## 🚧 Description
캠핑장 좋아요(찜) 관련 기능을 구현한다.
- 내가 그 캠핑장에 좋아요 눌렀는지 여부 조회
- 캠핑장 id로 해당 캠핑장 좋아요 개수 조회

## ✅ Todo
- [x] `campsite_like` 테이블 추가
- [x] 캠핑장 좋아요 토글 API 추가
- [ ] 캠핑장 조회 API 응답에 나의 좋아요 여부 포함
