### ISSUE TITLE
[BE] feat: 특정 캠핑장의 방 목록 조회 API 구현 

### ISSUE THREAD

**Issue by cheesecat47** [d106-campu/campu#113]
## 🚧 Description
특정 캠핑장의 방 목록 조회 API를 구현한다.

## ✅ Todo
- [x] 방 더미 데이터 추가
- [x] 방 조회 API 엔드포인트 추가
- [x] 방 조회 로직 구현
