### ISSUE TITLE
[BE] feat: 이미지 관련 API 구현

### ISSUE THREAD

**Issue by nmhojo** [d106-campu/campu#147]
## 🚧 Description
이미지 관련 API를 구현한다.

## ✅ Todo
- [ ] 프로필 이미지 업로드 및 다운로드
- [ ] 캠핑장 대표 이미지, 배치도 업로드 및 다운로드
- [ ] 방 이미지 업로드 및 다운로드
