### ISSUE TITLE
[FE] feat: KakaoMap 커스텀 및 이벤트 처리

### ISSUE THREAD

**Issue by minnnnnk0** [d106-campu/campu#234]
## 🚧 Description

카카오맵 지도를 커스텀하고 이벤트를 처리합니다.

## ✅ Todo
- [x] 중심좌표를 기준으로 지도 위치 고정
- [x] 마커 클릭시 리스트에 이벤트 추가
- [x] 기타 지도 이용 커스텀
