### ISSUE TITLE
[FE] feat: 예약페이지 빈자리 알림 등록 및 삭제 API 통신

### ISSUE THREAD

**Issue by danbxx22** [d106-campu/campu#236]
## 🚧 Description

사용자는 예약페이지에서 빈자리 알림을 5개까지 등록 및 삭제할 수 있다.

## ✅ Todo
- [x] 빈자리 알림 등록 API 통신
- [x] 빈자리 알림 등록 횟수 초과 UI 구현
- [x] 빈자리 알림 삭제 API 통신
