### ISSUE TITLE
[FE] feat: 사장님 페이지 이미지 업로드 API 통신

### ISSUE THREAD

**Issue by minnnnnk0** [d106-campu/campu#271]
## 🚧 Description

사장님 페이지의 정보 수정 이미지 업로드 API 통신을 합니다.

## ✅ Todo
- [x] 캠핑장 대표 이미지 업로드 API
- [x] 캠핑장 배치도 이미지 업로드 API
- [x] 캠핑장 일반 이미지 업로드 API
