### ISSUE TITLE
[FE] feat: 메인페이지 ui 구현

### ISSUE THREAD

**Issue by minnnnnk0** [d106-campu/campu#28]
## 🚧 Description

메인페이지 ui를 구현한다.

## ✅ Todo
- [x] 메인 검색바 ui 구현
- [x] 내가 찜한 캠핑장 ui 구현
- [x] 캠핑 유형별 검색 ui 구현
- [x] 캠핑 테마별 검색 ui 구현
- [x] 메인페이지 문구 및 스타일 구현
