### ISSUE TITLE
[BE] setting: 프로젝트 생성 및 설정

### ISSUE THREAD

**Issue by hoing97s** [d106-campu/campu#3]
## 🚧 Description
Spring Boot 프로젝트를 생성하고 기본적인 설정을 한다.

## ✅ Todo
- [x] Spring Boot 프로젝트 생성
- [x] 필요 라이브러리 불러오기 
- [x] 패키지 구조 설계
