### ISSUE TITLE
[FE] feat: 마이페이지 예약 취소, 재예약 & 사장님 방 등록 API 연결

### ISSUE THREAD

**Issue by Agwii** [d106-campu/campu#326]
## 🚧 Description

마이페이지 내 예약내역에서 리뷰 작성 후의 "다시 예약하기" 및 "예약 취소하기"를 제공합니다.

## ✅ Todo
- [x] Status 변화를 감지한 후에 "예약 취소하기" API 연결
- [x] Status 변화를 감지한 후에 "다시 예약하기" 제공
- [x] 사장님 페이지 방 등록 POST 요청 API 연결
