### ISSUE TITLE
[BE] feat: 캠핑장 방 관련 CRUD 구현

### ISSUE THREAD

**Issue by hoing97s** [d106-campu/campu#343]
## 🚧 Description

사장님은 캠핑장에 관련된 방을 등록, 수정, 삭제, 조회를 할 수 있다.

## ✅ Todo
- [x] 캠핑장 방 등록 API
- [x] 캠핑장 방 목록 조회 API
- [x] 캠핑장 방 수정 API
- [x] 캠핑장 방 삭제 API
