### ISSUE TITLE
[FE] feat: 캠핑장 대표 이미지 컴포넌트 UI 구현

### ISSUE THREAD

**Issue by danbxx22** [d106-campu/campu#35]
## 🚧 Description

사용자는 예약 페이지에서 캠핑장의 대표 이미지를 확인할 수 있다.

## ✅ Todo
- [x] 사진 개수에 따라 grid로 영역 나누기
- [x] 사진 모두 보기 버튼 구현
- [x] 전체 사진 확인 페이지 구현
