### ISSUE TITLE
[BE] feat: 아이디, 닉네임, 휴대전화 중복확인 API

### ISSUE THREAD

**Issue by hoing97s** [d106-campu/campu#36]
## 🚧 Description

이메일 및 휴대전화 중복확인 API를 구현한다.

## ✅ Todo
- [x] 유저 엔티티 설계
- [x] 아이디 중복확인 API
- [x] 휴대폰 중복확인 API
- [x] 닉네임 중복확인 API
