### ISSUE TITLE
[FE] feat: 캠핑장 예약 페이지 기본 UI 설계 

### ISSUE THREAD

**Issue by danbxx22** [d106-campu/campu#48]
## 🚧 Description

캠핑장 예약 페이지 기본 UI를 구현한다. 

## ✅ Todo
- [x] 캠핑장 필수정보 UI 구현
- [x] 캠핑장 소개 UI 구현
- [x] 캠핑장 배치도 UI 구현
- [x] 시설 및 레저 UI 구현
- [x] 방문자 리뷰 UI 구현
- [x] 캠핑장 운영정책 UI 구현
- [x] 사업자 정보 UI 구현
