### ISSUE TITLE
[FE] feat: 사용자 리뷰 상세 페이지 UI 구현

### ISSUE THREAD

**Issue by danbxx22** [d106-campu/campu#73]
## 🚧 Description

사용자는 상세 리뷰를 확인할 수 있다.

## ✅ Todo
- [x] 페이지 경로 수정
- [x] 디렉토리 구조 수정
- [x] 리뷰 페이지에서 클릭 시 이동
- [x] 상세 리뷰 컴포넌트 구현
